# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://gatsbro.netlify.com # This url will display in the top-right of the CMS
media_library:
  name: uploadcare
  config:
    publicKey: 009bb36efd764b5f8050
    multiple: false
    tabs: 'file camera url facebook gdrive'
    effects: 'crop,rotate,enhance,grayscale'
    imageShrink: '2000x2000'
    previewStep: true
    clearable: true

collections: # A list of collections the CMS should be able to edit
  - name: 'pages'
    label: 'Pages'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:

      - file: 'content/pages/home.md'
        label: 'Accueil'
        name: 'home-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Title, name: title, widget: hidden }
          - { label: Featured Image, name: featuredImage, widget: hidden }
          - { label: Subtitle, name: subtitle, widget: hidden }
          - { label: Vidéo accueil titre, name: videoTitle, widget: string }
          - { label: Vidéo accueil, name: video, widget: file }
          - { label: Vidéo snapshot, name: videoPoster, widget: image }
          - { label: Texte intro, name: body, widget: markdown }
          - { label: Titre section 1, name: title1, widget: string }
          - { label: Image parallax 1, name: parallax1, widget: image }
          - { label: Texte section 1, name: section1, widget: markdown }
          - { label: Titre section 2, name: title2, widget: string }
          - { label: Image parallax 2, name: parallax2, widget: image }
          - { label: Texte section 2, name: section2, widget: markdown }
          - { label: Titre section 3, name: title3, widget: string }
          - { label: Image parallax 3, name: parallax3, widget: image }
          - { label: Texte section 3, name: section3, widget: markdown }
          - { label: Titre section 4, name: title4, widget: string }
          - { label: Image parallax 4, name: parallax4, widget: image }
          - { label: Texte section 4, name: section4, widget: markdown }
          - { label: Titre section 5, name: title5, widget: string }
          - { label: Image parallax 5, name: parallax5, widget: image }
          - { label: Texte section 5, name: section5, widget: markdown }
          - { label: Titre section 6, name: title6, widget: string }
          - { label: Image parallax 6, name: parallax6, widget: image }
          - { label: Texte section 6, name: section6, widget: markdown }
          - { label: Titre section 7, name: title7, widget: string }
          - { label: Image parallax 7, name: parallax7, widget: image }
          - { label: Texte section 7, name: section7, widget: markdown }
          
      - file: 'content/pages/moi.md'
        label: 'Présentation'
        name: 'presentation-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: DefaultPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Titre, name: title, widget: string }
          - { label: Image, name: featuredImage, widget: image }
          - { label: Subtitle, name: subtitle, widget: hidden }
          - { label: Texte, name: body, widget: markdown }
      
      - file: 'content/pages/legislation.md'
        label: 'Législation'
        name: 'legislation-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: DefaultPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Titre, name: title, widget: string }
          - { label: Image, name: featuredImage, widget: image }
          - { label: Subtitle, name: subtitle, widget: hidden }
          - { label: Texte section 1, name: section1, widget: markdown }
          - { label: Texte section 2, name: section2, widget: markdown }
          - { label: Texte section 3, name: section3, widget: markdown }
          - { label: Texte section 4, name: section4, widget: markdown }
          
      - file: 'content/pages/contact.md'
        label: 'Contact'
        name: 'contact-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ContactPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'contact' }
          - { label: Title, name: title, widget: hidden }
          - {
              label: Image,
              name: featuredImage,
              widget: image,
              options:
                { media_library: { config: { imageShrink: 2600x2600 } } },
            }
          - { label: Subtitle, name: subtitle, widget: hidden }
          - { label: Body, name: body, widget: hidden }
          - { label: Address, name: address, widget: hidden }
          - { label: Téléphone, name: phone, widget: string }
          - { label: Adresse email, name: email, widget: string }
          
      - file: 'content/pages/blog.md'
        label: 'Blog'
        name: 'blog-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: BlogIndex,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'blog' }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: featuredImage, widget: image }
          - { label: Subtitle, name: subtitle, widget: hidden }
          
  - name: posts
    label: Articles
    editor:
      preview: true
    folder: content/posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Template, name: template, widget: hidden, default: SinglePost }
      - { label: Title, name: title, widget: string }
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ['Published', 'Featured', 'Draft']
        default: 'Published'
      - { label: Date, name: date, widget: date }
      - {
          label: Image,
          name: featuredImage,
          widget: hidden,
          required: false,
        }
      - { label: Texte raccourci, name: excerpt, widget: text }
      - { label: Content, name: body, widget: markdown }
      - label: 'Categories'
        name: 'categories'
        widget: 'list'
        required: false
        fields:
          - label: 'Categorie'
            name: 'category'
            widget: 'relation'
            collection: 'postCategories'
            searchFields: ['title']
            valueField: 'title'
      
  - name: postCategories
    label: Catégories d'articles
    editor:
      preview: false
    folder: content/postCategories
    slug: '{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Template, name: template, widget: hidden, default: BlogIndex }
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: hidden, required: false }
      - {
          label: Image,
          name: featuredImage,
          widget: image,
          required: false,
        }
      
  - name: 'settings'
    label: 'Configuration'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - { label: Titre du site, name: siteTitle, widget: string }
          - { label: Url du site, name: siteUrl, widget: string, required: false }
          - {
              label: Description du site,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
          - {
              label: Google Analytics Tracking Id,
              name: googleTrackingId,
              widget: string,
              required: false,
            }